// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "cb0b1c6e-4f11-4c22-b1c3-9c9737f184f7");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1664208589);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1664210954);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{4dc721ab-05a7-4b48-b882-bba4a6e47040}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1663608492);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{be5c5914-7999-412b-9732-f192c375c81a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1663608494);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1664208589852");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1664230189852");
user_pref("browser.search.region", "UA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220923151236");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220923151236");
user_pref("browser.startup.homepage_override.mstone", "105.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1664210953);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1663608495528");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "105.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "UA");
user_pref("dom.push.userAgentID", "cec0dffe096043958bae9075b16220f3");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1664210955);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-uk@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20220923151236");
user_pref("extensions.lastAppVersion", "105.0.1");
user_pref("extensions.lastPlatformVersion", "105.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e6689e0e-ed38-496f-ab4a-a28e6d1560b1\",\"formautofill@mozilla.org\":\"230d8b2f-f403-4777-8f62-db100f519832\",\"pictureinpicture@mozilla.org\":\"6b9b8818-ac10-4efe-a23a-345af1662e37\",\"screenshots@mozilla.org\":\"dd0e2abb-cffb-45ab-af82-66333d9c3bdd\",\"webcompat-reporter@mozilla.org\":\"c6d4897b-c405-4647-b251-b33b18a39aff\",\"webcompat@mozilla.org\":\"fae8ae92-2732-48e9-923c-d59879c491bc\",\"default-theme@mozilla.org\":\"177d53d8-6137-41e8-b3f1-d70c0de4e9ca\",\"addons-search-detection@mozilla.com\":\"9de8e52a-67c0-4e87-a214-da01f68a5a13\",\"google@search.mozilla.org\":\"bae65c6f-67f8-43de-8b8b-7ddd084079cf\",\"wikipedia@search.mozilla.org\":\"08dd7ad6-1f37-48d8-a661-65d4c7cc6418\",\"bing@search.mozilla.org\":\"81e3ae63-45a8-44c7-976b-157910625c34\",\"ddg@search.mozilla.org\":\"bfb825b3-183d-4097-8b49-cae0a46a9053\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1663608497);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("gfx.blacklist.vaapi", 4);
user_pref("gfx.blacklist.vaapi.failureid", "FEATURE_FAILURE_VAAPI_TEST_FAILED");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-95-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"1e8d6038-6abe-4f32-a682-11389811c175\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 95% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-09-19T17:28:16.511Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1c493b7e-9eda-42c7-aba5-d50919d91e55");
user_pref("toolkit.startup.last_success", 1664210949);
user_pref("toolkit.telemetry.cachedClientID", "5a1c16e5-8b47-4e5a-a232-3c7bc2aaeb39");
user_pref("toolkit.telemetry.previousBuildID", "20220923151236");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
